### ISSUE TITLE
功能需求

### ISSUE THREAD

**Issue by k0afakst7i** [skyone-wzw/nginx-autoindex#9]
你好 能不能做个上传文件的功能，谢谢了

**Comment by skyone-wzw** [comment]
你好，关于文件上传，这个纯前端的程序显然不可能实现。

想要上传，需要后端或nginx插件的支持。建议使用类似 `filebrowser` 等文件管理程序，例如：

```yml
services:
  aria2-filebrowser:
    image: filebrowser/filebrowser:v2
    container_name: aria2-filebrowser
    restart: always
    volumes:
      - ./config:/app
      - ./files:/srv
    networks:
      - proxy
    logging: *x-logging
    working_dir: /app
    command: [ "-c", "/app/config.json" ]
```

```json
{
  "port": 80,
  "baseURL": "",
  "address": "",
  "log": "stdout",
  "database": "/app/database.db",
  "root": "/srv"
}
```

欢迎给出其他建议~
